# Generated by Django 2.0.2 on 2019-09-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('roll', models.CharField(max_length=7)),
                ('dept', models.CharField(max_length=200)),
                ('sec', models.CharField(max_length=2)),
                ('blood', models.CharField(max_length=5)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
